/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'admin-dashboard': RouteRecordInfo<'admin-dashboard', '/admin/dashboard', Record<never, never>, Record<never, never>>,
    'user-index': RouteRecordInfo<'user-index', '/admin/users', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/auth/login', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/auth/register', Record<never, never>, Record<never, never>>,
    'user-dashboard': RouteRecordInfo<'user-dashboard', '/user/dashboard', Record<never, never>, Record<never, never>>,
  }
}
